// Vehicle data - Cars and Bikes for RideRent
// This file contains all vehicle data including image paths

// Original paths are relative to pages directory (../images/...)
// For index.html page, we'll modify these paths in the script.js file

// Cars data
const carsData = [
    {
        id: 1,
        name: "Toyota Camry",
        type: "car",
        category: "sedan",
        price: 4500,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "25 mpg",
        features: ["Bluetooth", "Backup Camera", "Cruise Control", "USB Port"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Toyota%20Camry.jpg"
    },
    {
        id: 2,
        name: "Honda Civic",
        type: "car",
        category: "sedan",
        price: 4125,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "30 mpg",
        features: ["Bluetooth", "Backup Camera", "Apple CarPlay", "Android Auto"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Honda%20Civic.jpg"
    },
    {
        id: 3,
        name: "Ford Mustang",
        type: "car",
        category: "sports",
        price: 7500,
        year: 2023,
        seats: 4,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "20 mpg",
        features: ["Convertible", "Leather Seats", "Premium Sound System", "Performance Package"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Ford%20Mustang.jpg"
    },
    {
        id: 4,
        name: "Jeep Wrangler",
        type: "car",
        category: "suv",
        price: 6750,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "17 mpg",
        features: ["4x4", "Removable Top", "Off-Road Capability", "Bluetooth"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Jeep%20Wrangler.jpg"
    },
    {
        id: 5,
        name: "BMW 4 Series",
        type: "car",
        category: "luxury",
        price: 13500,
        year: 2023,
        seats: 4,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "25 mpg",
        features: ["Leather Seats", "Navigation", "Premium Sound System", "Heated Seats"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/bmw-4-series-coupe-m-automobiles-sd-individual-01.jpg"
    },
    {
        id: 6,
        name: "Audi A8",
        type: "car",
        category: "luxury",
        price: 1500,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        mileage: "28 mpg",
        features: ["Leather Seats", "Navigation", "Premium Sound System", "Massage Seats", "Executive Package"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Audi%20A8.jpg"
    },
    {
        id: 7,
        name: "Range Rover Sport",
        type: "car",
        category: "suv",
        price: 1400,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "18 mpg",
        features: ["Leather Seats", "Navigation", "Premium Sound System", "Panoramic Roof", "Off-Road Capability"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Range%20Rover%20Sport.jpg"
    },
    {
        id: 8,
        name: "Tesla Model 3",
        type: "car",
        category: "electric",
        price: 1100,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        mileage: "358 miles range",
        features: ["Autopilot", "Navigation", "Premium Sound System", "Heated Seats", "Supercharging"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/55f59f66cd1b7bc95d64556813398760.jpg"
    },
    {
        id: 9,
        name: "Mercedes-Benz S-Class",
        type: "car",
        category: "luxury",
        price: 1800,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        mileage: "25 mpg",
        features: ["Leather Seats", "Navigation", "Premium Sound System", "Massage Seats", "Executive Package", "Ambient Lighting"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Mercedes-Benz%20S-Class.jpg"
    },
    {
        id: 10,
        name: "Porsche 911",
        type: "car",
        category: "sports",
        price: 15000,
        year: 2023,
        seats: 2,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "22 mpg",
        features: ["Sport Exhaust", "Sport Chrono Package", "Bose Sound System", "Sport Suspension", "Launch Control"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Porsche%20911.webp"
    },
    {
        id: 11,
        name: "Volkswagen Golf GTI",
        type: "car",
        category: "sports",
        price: 6375,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "28 mpg",
        features: ["Sport Suspension", "LED Headlights", "Apple CarPlay", "Android Auto", "Performance Package"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Volkswagen%20Golf%20GTI.avif"
    },
    {
        id: 12,
        name: "Hyundai Tucson",
        type: "car",
        category: "suv",
        price: 5250,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        mileage: "32 mpg",
        features: ["All-Wheel Drive", "Panoramic Sunroof", "Bluetooth", "Backup Camera", "Smart Cruise Control"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Hyundai%20Tucson.jpg"
    },
    {
        id: 13,
        name: "Toyota RAV4",
        type: "car",
        category: "suv",
        price: 5250,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        mileage: "35 mpg",
        features: ["All-Wheel Drive", "Bluetooth", "Backup Camera", "Lane Departure Warning", "Adaptive Cruise Control"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Toyota%20RAV4.jpg"
    },
    {
        id: 14,
        name: "Nissan Leaf",
        type: "car",
        category: "electric",
        price: 7500,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        mileage: "226 miles range",
        features: ["ProPilot Assist", "Apple CarPlay", "Android Auto", "Bose Sound System", "Fast Charging"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Nissan%20Leaf.avif"
    },
    {
        id: 15,
        name: "Lexus ES",
        type: "car",
        category: "luxury",
        price: 13000,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Hybrid",
        mileage: "40 mpg",
        features: ["Leather Seats", "Navigation", "Premium Sound System", "Lane Departure Warning", "Adaptive Cruise Control"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Lexus%20ES.jpg"
    },
    {
        id: 16,
        name: "Mazda CX-5",
        type: "car",
        category: "suv",
        price: 6000,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "28 mpg",
        features: ["All-Wheel Drive", "Bluetooth", "Backup Camera", "Lane Departure Warning", "Adaptive Cruise Control"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Mazda%20CX-5.avif"
    },
    {
        id: 17,
        name: "Chevrolet Bolt EV",
        type: "car",
        category: "electric",
        price: 7000,
        year: 2023,
        seats: 5,
        transmission: "Automatic",
        fuelType: "Electric",
        mileage: "259 miles range",
        features: ["One-Pedal Driving", "Apple CarPlay", "Android Auto", "Fast Charging", "Regenerative Braking"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Chevrolet%20Bolt%20EV.avif"
    },
    {
        id: 18,
        name: "Kia Telluride",
        type: "car",
        category: "suv",
        price: 6000,
        year: 2023,
        seats: 7,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: "23 mpg",
        features: ["All-Wheel Drive", "Panoramic Sunroof", "Bluetooth", "Backup Camera", "Third Row Seating"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/cars/Kia%20Telluride.jpg"
    }
];

// Bikes data
const bikesData = [
    {
        id: 101,
        name: "Honda CBR1000RR",
        type: "bike",
        category: "sport",
        price: 8000,
        year: 2023,
        engine: "1000cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "35 mpg",
        features: ["ABS", "Traction Control", "Quick Shifter", "Riding Modes"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/1db9f5ae49f4e6005b88934f539eef25.jpg"
    },
    {
        id: 102,
        name: "Yamaha MT-07",
        type: "bike",
        category: "naked",
        price: 6500,
        year: 2023,
        engine: "689cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "50 mpg",
        features: ["ABS", "LCD Display", "LED Lights", "Dual-Channel ABS"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Yamaha%20MT-07.jpg"
    },
    {
        id: 103,
        name: "Kawasaki Ninja ZX-10R",
        type: "bike",
        category: "sport",
        price: 8500,
        year: 2023,
        engine: "998cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "30 mpg",
        features: ["ABS", "Traction Control", "Quick Shifter", "Cornering Management Function"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Kawasaki%20Ninja%20ZX-10R.jpg"
    },
    {
        id: 104,
        name: "Ducati Panigale V4",
        type: "bike",
        category: "sport",
        price: 12000,
        year: 2023,
        engine: "1103cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "30 mpg",
        features: ["ABS", "Traction Control", "Quick Shifter", "Electronic Suspension", "Riding Modes"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Ducati%20Panigale%20V4.jpg"
    },
    {
        id: 105,
        name: "BMW R 1250 GS",
        type: "bike",
        category: "adventure",
        price: 10000,
        year: 2023,
        engine: "1254cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "45 mpg",
        features: ["ABS", "Traction Control", "Electronic Suspension", "Riding Modes", "Heated Grips"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/BMW%20R%201250%20GS.jpg"
    },
    {
        id: 106,
        name: "Harley-Davidson Street Glide",
        type: "bike",
        category: "cruiser",
        price: 11000,
        year: 2023,
        engine: "1868cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "40 mpg",
        features: ["ABS", "Infotainment System", "Cruise Control", "Saddlebags", "Premium Audio"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Harley-Davidson%20Street%20Glide.jpg"
    },
    {
        id: 107,
        name: "Triumph Street Triple",
        type: "bike",
        category: "naked",
        price: 7500,
        year: 2023,
        engine: "765cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "45 mpg",
        features: ["ABS", "Traction Control", "Quick Shifter", "Riding Modes"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Triumph%20Street%20Triple.jpg"
    },
    {
        id: 108,
        name: "Honda Rebel 500",
        type: "bike",
        category: "cruiser",
        price: 6000,
        year: 2023,
        engine: "471cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "60 mpg",
        features: ["ABS", "LED Lights", "Digital Display", "Slipper Clutch"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Honda%20Rebel%20500.jpg"
    },
    {
        id: 109,
        name: "Suzuki Hayabusa",
        type: "bike",
        category: "sport",
        price: 9500,
        year: 2023,
        engine: "1340cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "35 mpg",
        features: ["ABS", "Traction Control", "Quick Shifter", "Riding Modes", "Launch Control"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Suzuki%20Hayabusa.jpg"
    },
    {
        id: 110,
        name: "KTM 390 Duke",
        type: "bike",
        category: "naked",
        price: 5500,
        year: 2023,
        engine: "373cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "65 mpg",
        features: ["ABS", "TFT Display", "LED Lights", "Traction Control", "Riding Modes"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/KTM%20390%20Duke.webp"
    },
    {
        id: 111,
        name: "Aprilia RS 660",
        type: "bike",
        category: "sport",
        price: 9000,
        year: 2023,
        engine: "659cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "45 mpg",
        features: ["ABS", "Traction Control", "Quick Shifter", "Riding Modes", "TFT Display"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Aprilia%20RS%20660.webp"
    },
    {
        id: 112,
        name: "Kawasaki Versys 650",
        type: "bike",
        category: "adventure",
        price: 7500,
        year: 2023,
        engine: "649cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "50 mpg",
        features: ["ABS", "Traction Control", "Adjustable Windscreen", "Heated Grips", "LED Lights"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Kawasaki%20Versys%20650.png"
    },
    {
        id: 113,
        name: "Yamaha XSR900",
        type: "bike",
        category: "naked",
        price: 6375,
        year: 2023,
        engine: "847cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "45 mpg",
        features: ["ABS", "Traction Control", "Quick Shifter", "Riding Modes", "LED Lights"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Yamaha%20XSR900.avif"
    },
    {
        id: 114,
        name: "Ducati Multistrada V4",
        type: "bike",
        category: "adventure",
        price: 9000,
        year: 2023,
        engine: "1158cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "35 mpg",
        features: ["ABS", "Traction Control", "Electronic Suspension", "Riding Modes", "Radar System"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Ducati%20Multistrada%20V4.jpg"
    },
    {
        id: 115,
        name: "Triumph Bonneville T120",
        type: "bike",
        category: "standard",
        price: 9500,
        year: 2023,
        engine: "1200cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "45 mpg",
        features: ["ABS", "Traction Control", "Heated Grips", "LED Lights", "USB Charging"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Triumph%20Bonneville%20T120.avif"
    },
    {
        id: 116,
        name: "Kawasaki Z900",
        type: "bike",
        category: "naked",
        price: 6000,
        year: 2023,
        engine: "948cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "45 mpg",
        features: ["ABS", "Traction Control", "Riding Modes", "LED Lights", "TFT Display"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Kawasaki%20Z900.webp"
    },
    {
        id: 117,
        name: "BMW F 900 R",
        type: "bike",
        category: "naked",
        price: 6375,
        year: 2023,
        engine: "895cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "45 mpg",
        features: ["ABS", "Traction Control", "Riding Modes", "LED Lights", "TFT Display"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/BMW%20R%201250%20GS.jpg"
    },
    {
        id: 118,
        name: "Honda Africa Twin",
        type: "bike",
        category: "adventure",
        price: 11000,
        year: 2023,
        engine: "1084cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "45 mpg",
        features: ["ABS", "Traction Control", "Electronic Suspension", "Riding Modes", "Heated Grips"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Honda%20Africa%20Twin.avif"
    },
    {
        id: 119,
        name: "Indian Scout",
        type: "bike",
        category: "cruiser",
        price: 10000,
        year: 2023,
        engine: "1133cc",
        transmission: "Manual",
        fuelType: "Gasoline",
        mileage: "45 mpg",
        features: ["ABS", "Traction Control", "LED Lights", "USB Charging", "Premium Audio"],
        available: true,
        image: "https://ik.imagekit.io/r5wsp5fo2/bikes/Indian%20Scout.webp"
    }
];

// Combined data for use in the main script
const allVehicles = [...carsData, ...bikesData]; 